apiVersion: v1
kind: Service
metadata:
  name: production-service
  namespace: prod  # Ensure this matches your deployment's namespace
spec:
  selector:
    app: production-app  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80          # External port (browser)
      targetPort: 8080  # Port inside the container
  type: LoadBalancer  # Makes it accessible via an external IP
